export const GRAPH_ADD_EDGE = Symbol('graph-add-edge')
export const GRAPH_ADD_VERTEX = Symbol('graph-add-vertex')
export const GRAPH_CLEAR = Symbol('graph-clear')
export const GRAPH_LOAD = Symbol('graph-load')
export const GRAPH_REDO = Symbol('graph-redo')
export const GRAPH_REMOVE_EDGE = Symbol('graph-remove-edge')
export const GRAPH_REMOVE_VERTEX = Symbol('graph-remove-vertex')
export const GRAPH_UNDO = Symbol('graph-undo')
export const GRAPH_UPDATE_EDGE = Symbol('graph-update-edge')
export const GRAPH_UPDATE_VERTEX = Symbol('graph-update-vertex')

export const PROJECT_ADD = Symbol('project-add')
export const PROJECT_GET = Symbol('project-get')
export const PROJECT_LOAD = Symbol('project-load')
export const PROJECT_REMOVE = Symbol('project-remove')
export const PROJECT_UPDATE = Symbol('project-update')

export const PARTICIPANT_ADD = Symbol('participant-add')
export const PARTICIPANT_GET = Symbol('participant-get')
export const PARTICIPANT_LIST = Symbol('participant-list')
export const PARTICIPANT_REMOVE = Symbol('participant-remove')
export const PARTICIPANT_UPDATE = Symbol('participant-update')

export const CALC_MORPH = Symbol('calc-morph')

export const CALC_LAYOUT = Symbol('calc-layout')

export const ANALYSIS_INIT = Symbol('analysis-init')
export const ANALYSIS_SELECT_VERTEX = Symbol('analysis-select-vertex')
export const ANALYSIS_SELECT_VERTICES_BY_WORD = Symbol('analysis-select-vertices-by-word')
export const ANALYSIS_SET_THRESHOLD = Symbol('analysis-set-threshold')
export const ANALYSIS_UPDATE_PARTICIPANTS = Symbol('analysis-update-participants')
